[project]
name = "arcaea-rank-data"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "coloredlogs>=15.0.1",
    "pytelegrambotapi>=4.27.0",
    "requests>=2.34.2",
    "telebot>=0.0.5",
]

[tool.uv]
package = false

[[tool.mypy.overrides]]
module = ["telebot.*", "coloredlogs.*"]
disable_error_code = ["import-untyped"]

[dependency-groups]
dev = [
    "types-requests>=2.33.0.20260518",
]
