name: 'Daily Autofetch Job'

on: 
  workflow_dispatch:
  schedule:
    - cron: '25,50 0-10/2 * * *'

jobs:
  file_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      FILECHECK_OK: ${{ steps.file_check.outputs.ret }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Check file exists
        id: file_check
        run: |
          python filecheck.py
          echo ret=$? >> "$GITHUB_OUTPUT"
  main_job:
    runs-on: ubuntu-latest
    needs: file_check
    permissions:
      contents: write
    steps:
      - name: TEST 111
        run: echo "Detected file check is not OK, main job is running $fo"
        env:
          fo: ${{needs.file_check.outputs.FILECHECK_OK}}
      # - name: Install deps
      #   run: pip install -r requirements.txt
      # - name: Check public IP
      #   uses: haythem/public-ip@v1.3
      # - name: Do the run
      #   run: python main.py
      # - name: Commit changes
      #   # https://github.com/stefanzweifel/git-auto-commit-action
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Apply automatic data changes
