name: 'Daily Autofetch Job'

on: 
  workflow_dispatch:
  schedule:
    - cron: '25,50 0-10/2 * * *'

jobs:
  file_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Check file exists
        id: file_check
        run: |
          python filecheck.py
  main_job:
    runs-on: ubuntu-latest
    needs: file_check
    if: env.FILE_EXISTS == 'False'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Check public IP
        uses: haythem/public-ip@v1.3
      - name: Do the run
        run: python main.py
      - name: Commit changes
        if: env.PAID_DATA_ERRORED == 'false' && env.FREE_DATA_ERRORED == 'false'
        # https://github.com/stefanzweifel/git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic data changes
